### ISSUE TITLE
Import from opentdb not working

### ISSUE THREAD

**Issue by mrtumnus** [bmcgonag/trivia-challenge#1]
Hi, I just followed through your instructions to install the app.  It worked rather well, considering all the steps and dependencies.

Any update on the import function?  I see on the main page that it's not working at the moment.  I do get an "API Success" message, but no categories or questions are imported.

I might take a moment to look into it at some point, given that it looks like it's been a few years since this project has been touched.

**Comment by bmcgonag** [comment]
Thanks for the kick in the back-side that i needed.  I have updated the project to use the newest MeteorJS framework, which also brings it to NodeJS 12.16.1.  I'll update the readme soon. 

I found that the opntdb page isn't responding anymore, so I'm guessing it's gone, sadly.  I've found a couple of other sources of trivia questions, but they are only question and answer, with no multiple choice or TF options today.  I'll do my best to get some of those updated to be more conducive to my app, but that will definitely take a while.  If you find an api that has what we are looking for, I'm happy to try and get it added in.

**Comment by mrtumnus** [comment]
Thanks, @bmcgonag.  Actually, the opentdb page does respond, it just takes a while.  I was able to load the main page and browse around a bit.

**Comment by mrtumnus** [comment]
Or at least it was loading yesterday.  Looks like it's down now.

**Comment by bmcgonag** [comment]
Ok, I'll check back, maybe the site is just down.  Meanwhile, It may be
good for me to just do the work to push out an API of my own that I can
make sure is up and running", or at the very least make some trivia packs
as I complete a couple of hundred questions at a time, and make them
available, so they can be imported pretty easily.

Brian McGonagill
